# Generated by Django 5.2 on 2025-05-02 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_virtual',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, default='upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
