# Generated by Django 5.2 on 2025-05-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionattendance_session_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file_type',
        ),
    ]
