# Generated by Django 5.2 on 2025-05-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_resource_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('txt', 'TXT')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
