# Generated by Django 5.2 on 2025-05-03 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_resource_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='group',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('png', 'PNG'), ('jpg', 'JPG'), ('js', 'JavaScript'), ('txt', 'Text')], max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'user')},
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('session_reminders', models.BooleanField(default=True)),
                ('group_messages', models.BooleanField(default=True)),
                ('resource_updates', models.BooleanField(default=True)),
                ('new_members', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.PositiveIntegerField(default=0)),
                ('sessions_attended', models.PositiveIntegerField(default=0)),
                ('resources_shared', models.PositiveIntegerField(default=0)),
                ('groups_joined', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
